<?php

$host = $_SERVER['HTTP_HOST'];
$serverName = php_uname('n');

define ("R_VERSION", '0.5');

define ("FOLDER_ADMIN",		"admin/");											// Decription des dossiers du site
define ("FOLDER_CLASSES",	"classes/");
define ("FOLDER_CONFIG",	"config/");
define ("FOLDER_CSS",		"css/");
define ("FOLDER_FCT",		"fct/");
define ("FOLDER_GFX",		"gfx/");
define ("FOLDER_JS",		"js/");
define ("FOLDER_INC",		"inc/");
define ("FOLDER_MAILS",		"mails/");
define ("FOLDER_PAGES",		"pages/");


?>
